/**
 * Pure serializers that translate public options into the plain map sent to
 * the native layer. Kept free of native imports so they can be unit-tested
 * (AGENTS.md §49, §41).
 */
import { YtDlpError } from './errors';
import type { CookieOptions, DownloadOptions, ExtractOptions } from './types';

export function serializeExtractOptions(
  options: ExtractOptions | undefined
): Record<string, unknown> {
  if (!options) return {};
  const out: Record<string, unknown> = {};
  if (options.cookies) out.cookies = serializeCookies(options.cookies);
  if (options.proxy) out.proxy = options.proxy;
  if (options.userAgent || options.headers) {
    const headers: Record<string, string> = { ...(options.headers ?? {}) };
    if (options.userAgent) headers['User-Agent'] = options.userAgent;
    out.headers = headers;
  }
  return out;
}

export function serializeDownloadOptions(options: DownloadOptions): Record<string, unknown> {
  const out: Record<string, unknown> = { url: options.url };
  if (options.format) out.format = options.format;
  if (options.output) {
    const output: Record<string, unknown> = {};
    if (options.output.directory) output.directory = options.output.directory;
    if (options.output.filename) output.filename = options.output.filename;
    if (Object.keys(output).length > 0) out.output = output;
  }
  if (options.merge != null) out.merge = options.merge;
  if (options.ffmpeg?.location) {
    const location = options.ffmpeg.location.trim();
    if (!location) {
      throw new YtDlpError('PROCESSING_FAILED', 'ffmpeg.location must not be empty.');
    }
    out.ffmpeg = { location };
  }
  if (options.cookies) out.cookies = serializeCookies(options.cookies);
  if (options.userAgent || options.headers) {
    const headers: Record<string, string> = { ...(options.headers ?? {}) };
    if (options.userAgent) headers['User-Agent'] = options.userAgent;
    out.headers = headers;
  }
  if (options.referer) out.referer = options.referer;
  if (options.proxy) out.proxy = options.proxy;
  if (options.playlist) {
    const playlist: Record<string, unknown> = {};
    if (options.playlist.enabled != null) playlist.enabled = options.playlist.enabled;
    if (options.playlist.start != null) playlist.start = options.playlist.start;
    if (options.playlist.end != null) playlist.end = options.playlist.end;
    if (Object.keys(playlist).length > 0) out.playlist = playlist;
  }
  if (options.network) {
    const network: Record<string, unknown> = {};
    if (options.network.timeout != null) network.timeout = options.network.timeout;
    if (options.network.retries != null) network.retries = options.network.retries;
    if (Object.keys(network).length > 0) out.network = network;
  }
  if (options.subtitles) {
    const subtitles: Record<string, unknown> = {};
    if (options.subtitles.enabled != null) subtitles.enabled = options.subtitles.enabled;
    if (options.subtitles.languages?.length) subtitles.languages = options.subtitles.languages;
    if (options.subtitles.autoGenerated != null)
      subtitles.autoGenerated = options.subtitles.autoGenerated;
    if (Object.keys(subtitles).length > 0) out.subtitles = subtitles;
  }
  return out;
}

export function serializeCookies(cookies: CookieOptions): Record<string, unknown> {
  if (cookies.source === 'file' && cookies.path) {
    return { path: cookies.path };
  }
  throw new YtDlpError('INVALID_URL', 'Cookies must reference a cookies file path.');
}
