/**
 * Public types for expo-ytdlp-native.
 *
 * These types are the stable contract of the package. Native details never
 * leak into this surface (see AGENTS.md §68).
 */
import type { YtDlpError } from './errors';

export type DownloadStatus =
  'queued' | 'extracting' | 'downloading' | 'processing' | 'completed' | 'cancelled' | 'failed';

export type DownloadPhase = 'extracting' | 'downloading' | 'processing';

export interface Thumbnail {
  url: string;
  width?: number;
  height?: number;
  resolution?: string;
  id?: string;
}

/** Normalized media information. Every field is optional except `formats`. */
export interface VideoInfo {
  id?: string;
  title?: string;
  description?: string;
  uploader?: string;
  uploaderId?: string;
  uploaderUrl?: string;
  channel?: string;
  channelId?: string;
  channelUrl?: string;
  webpageUrl?: string;
  originalUrl?: string;
  thumbnail?: string;
  thumbnails?: Thumbnail[];
  duration?: number;
  durationString?: string;
  uploadDate?: string;
  timestamp?: number;
  viewCount?: number;
  likeCount?: number;
  commentCount?: number;
  ageLimit?: number;
  isLive?: boolean;
  wasLive?: boolean;
  extractor?: string;
  extractorKey?: string;
  webpageUrlDomain?: string;
  formats: Format[];
}

/** Normalized format model. Unknown native values become `undefined`. */
export interface Format {
  id: string;
  url?: string;
  ext?: string;
  protocol?: string;
  format?: string;
  formatNote?: string;
  width?: number;
  height?: number;
  fps?: number;
  vcodec?: string;
  acodec?: string;
  abr?: number;
  vbr?: number;
  tbr?: number;
  filesize?: number;
  filesizeApprox?: number;
  quality?: number;
  audioOnly: boolean;
  videoOnly: boolean;
  hasVideo: boolean;
  hasAudio: boolean;
  language?: string;
  container?: string;
}

export interface OutputOptions {
  /**
   * Directory name, relative to the app-specific external storage directory.
   * Single path segments only; `..` is rejected.
   */
  directory?: string;
  /**
   * yt-dlp output template, e.g. `%(title)s.%(ext)s`.
   * Static parts are sanitized; template directives are preserved.
   */
  filename?: string;
}

export interface SubtitleOptions {
  enabled?: boolean;
  languages?: string[];
  autoGenerated?: boolean;
}

export interface CookieOptions {
  source: 'file';
  path: string;
}

export interface NetworkOptions {
  timeout?: number;
  retries?: number;
}

export interface PlaylistOptions {
  enabled?: boolean;
  start?: number;
  end?: number;
}

export interface ExtractOptions {
  /** Cookies used during extraction (e.g. for login-gated sources). */
  cookies?: CookieOptions;
  /** Additional HTTP headers sent during extraction. Never logged. */
  headers?: Record<string, string>;
  /** Custom `User-Agent`. */
  userAgent?: string;
  proxy?: string;
}

export interface DownloadOptions {
  url: string;
  /** Raw yt-dlp format expression, e.g. `best`, `bestvideo+bestaudio`. */
  format?: string;
  output?: OutputOptions;
  merge?: boolean;
  subtitles?: SubtitleOptions;
  cookies?: CookieOptions;
  /** Additional HTTP headers. Validated; secrets are never logged. */
  headers?: Record<string, string>;
  userAgent?: string;
  referer?: string;
  proxy?: string;
  playlist?: PlaylistOptions;
  network?: NetworkOptions;
}

export interface DownloadProgress {
  taskId: string;
  status: DownloadStatus;
  phase: DownloadPhase;
  percent?: number;
  downloadedBytes?: number;
  totalBytes?: number;
  speedBytesPerSecond?: number;
  etaSeconds?: number;
  filename?: string;
}

export interface DownloadResult {
  taskId: string;
  path?: string;
  uri?: string;
  filename?: string;
  mimeType?: string;
  size?: number;
  duration?: number;
}

export type DownloadEventType = 'progress' | 'state' | 'completed' | 'error' | 'cancelled';

export interface DownloadEvent {
  taskId: string;
  type: DownloadEventType;
  status: DownloadStatus;
  phase: DownloadPhase;
  progress?: DownloadProgress;
  result?: DownloadResult;
  error?: {
    code: string;
    message: string;
  };
}

export type DownloadStateEvent = {
  taskId: string;
  status: DownloadStatus;
};

export interface Subscription {
  remove(): void;
}

export interface DownloadTask {
  id: string;
  cancel(): Promise<void>;
  getStatus(): Promise<DownloadStatus>;
  getProgress(): Promise<DownloadProgress | null>;
  addListener(event: 'progress', listener: (progress: DownloadProgress) => void): Subscription;
  addListener(event: 'state', listener: (state: DownloadStateEvent) => void): Subscription;
  addListener(event: 'completed', listener: (result: DownloadResult) => void): Subscription;
  addListener(event: 'error', listener: (error: YtDlpError) => void): Subscription;
}

export interface YtDlpVersion {
  ytDlp: string;
  library: string;
}

export type YtDlpErrorCode =
  | 'INVALID_URL'
  | 'EXTRACTION_FAILED'
  | 'DOWNLOAD_FAILED'
  | 'CANCELLED'
  | 'FORMAT_UNAVAILABLE'
  | 'NETWORK_ERROR'
  | 'AUTHENTICATION_REQUIRED'
  | 'GEO_RESTRICTED'
  | 'PRIVATE_CONTENT'
  | 'AGE_RESTRICTED'
  | 'PROCESSING_FAILED'
  | 'STORAGE_ERROR'
  | 'INIT_FAILED'
  | 'UNSUPPORTED_PLATFORM'
  | 'UNKNOWN';
